name: build and lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - release/*

jobs:
  lint:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: "3.7.5"
          channel: 'stable'
      - name: flutter pub get
        run: flutter pub get
      - name: build_runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
      - run: flutter build apk --debug --flavor local -t lib/main_local.dart --dart-define=GA_TRACKER_ID=UA-xxxxx-x --dart-define=ANDROID_GOOGLE_MAP_API_KEY=xxxxx --dart-define=IOS_GOOGLE_MAP_API_KEY=xxxxx --dart-define=API_KEY=xxxxx
        # 後でtxtの中身をcatとかにする
      - name: flutter analyze to txt
        run: flutter analyze > flutter_analyze_report.txt
      - name: setup ruby
        if: ${{ failure() }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: run danger
        if: ${{ failure() }}
        uses: MeilCli/danger-action@v5.0.2
        with:
          plugins_file: Gemfile
          install_path: vendor/bundle
          danger_file: Dangerfile
          danger_id: danger-pr
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.ACCESS_TOKEN }}

# 以下はself-hostedが使えるようになったら

#name: build and lint
#
#on:
#  pull_request:
#    types: [opened, synchronize, reopened]
#  push:
#    branches:
#      - release/*
#
#env:
#  ANDROID_SDK_ROOT: /usr/lib/android-sdk
#  ANDROID_HOME: /usr/lib/android-sdk
#  ImageOS: ubuntu20.04
#
#jobs:
#  lint:
#    name: flutter analyze
#    runs-on: self-hosted
#    steps:
#      - name: set up repository
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: set up java
#        uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"
#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v2
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: "2.8.1"
#          channel: 'stable'
#      - name: flutter pub get
#        run: flutter pub get
#      - name: test & build_runner
#        run: |
#          flutter packages pub run build_runner build --delete-conflicting-outputs
#          flutter test
#          flutter build apk --debug --flavor local -t lib/main_local.dart --dart-define=GA_TRACKER_ID=UA-xxxxx-x --dart-define=ANDROID_GOOGLE_MAP_API_KEY=xxxxx --dart-define=IOS_GOOGLE_MAP_API_KEY=xxxxx --dart-define=API_KEY=xxxxx
#      - name: flutter analyze
#        run: flutter analyze > flutter_analyze_report.txt
#      - name: setup ruby
#        if: ${{ failure() }}
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.7
#          bundler-cache: true
#      - name: run danger
#        if: ${{ failure() }}
#        uses: MeilCli/danger-action@v5.0.2
#        with:
#          plugins_file: Gemfile
#          install_path: vendor/bundle
#          danger_file: Dangerfile
#          danger_id: danger-pr
#        env:
#          DANGER_GITHUB_API_TOKEN: ${{ secrets.ACCESS_TOKEN }}
