name: netsuper
description: IY Netsuper APP

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+53

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.7.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: 1.24.0
  firebase_crashlytics: 2.9.0
  firebase_performance: 0.7.1+5
  # null Safety未対応のライブラリ
  dio_firebase_performance: 0.3.1-dev.3
  firebase_analytics: 9.3.8
  flutter_flavor: 3.1.1
  get_it: 7.6.0
  dio: 4.0.6
  freezed_annotation: 2.2.0
  json_annotation: 4.8.1
  provider: 6.0.5
  flutter_state_notifier: 0.7.3
  state_notifier: 0.7.2+1
  simple_logger: 1.9.0+2
  flutter_svg: 2.0.5
  enum_to_string: 2.0.1
  device_info_plus: 5.0.5
  flutter_cache_manager: 3.3.0
  google_maps_flutter: 2.3.0
  custom_refresh_indicator: 1.2.1
  flash: 2.0.5+1
  flutter_secure_storage: 5.1.2
  shared_preferences: 2.1.1
  intl: 0.17.0
  geolocator: 8.2.1
  table_sticky_headers: 2.0.5
  google_place: 0.4.7
  package_info_plus: 1.4.3+1
  video_player: 2.6.1
  dotted_border: 2.0.0+3
  open_store: 0.2.4
  qr_flutter: 4.0.0
  tuple: 2.0.1
  native_webview: 1.4.0
  url_launcher: 6.1.11
  uuid: 3.0.7
  version: 3.0.2
  carousel_slider: 4.2.1
  # TODO visibility_detector >=0.3.2 which requires Flutter SDK version >=2.10.5
  visibility_detector: 0.2.2
  adjust_sdk: 4.33.1
  flutter_html: 3.0.0-alpha.6
  image_size_getter: 2.1.2
  firebase_auth_platform_interface: 6.7.0
  flutter_web_auth_2: 2.1.4
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: 13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  build_runner: 2.3.3
  flutter_gen_runner: 5.3.1
  freezed: 2.3.5
  json_serializable: 6.6.2
  import_path_converter: 1.0.1
  import_sorter: 4.6.0

flutter_gen:
  output: lib/gen
  line_length: 120

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/js/

import_path_converter:
  relative: true
  ignored_files: # Optional, defaults to []
    - \/test\/*
    - \/lib\/(\w+\/)+\w+\.gen\.dart
    - \/lib\/(\w+\/)+\w+\.freezed\.dart
    - \/lib\/(\w+\/)+\w+\.g\.dart

import_sorter:
  comments: false
  ignored_files: # Optional, defaults to []
    - \/lib\/(\w+\/)+\w+\.gen\.dart
    - \/lib\/(\w+\/)+\w+\.freezed\.dart
    - \/lib\/(\w+\/)+\w+\.g\.dart
